ANOVA

In [78]:
import numpy as np
from scipy import stats

In [79]:
H0 = ('различий среднего роста среди взрослых футболистов, хоккеистов и штангистов нет.')
H1 = ('различия среднего роста среди взрослых футболистов, хоккеистов и штангистов есть.')


In [80]:
football= np.array([173, 175, 180, 178, 177, 185, 183, 182])
football

array([173, 175, 180, 178, 177, 185, 183, 182])

In [81]:
hockey = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
hockey

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [82]:
shtang = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
shtang

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [83]:
alpha = 0.05

In [88]:
statistic, pvalue = stats.f_oneway(football, hockey, shtang)
print(pvalue)

0.010482206918698694


In [87]:

if pvalue > alpha:
    print('ОТВЕТ: Принимаем гипотезу H0:', H0, 'На уровне значимости 5%.')
else:
    print('ОТВЕТ: Принимаем гипотезу H1:', H1, 'На уровне значимости 5%.')

ОТВЕТ: Принимаем гипотезу H1: различия среднего роста среди взрослых футболистов, хоккеистов и штангистов есть. На уровне значимости 5%.
