In [47]:
import pandas as pd
import numpy as np

Задача № 1

In [48]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [49]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [50]:
n = len(X)
n

10

In [51]:
X = zp
y = ks

In [52]:
b = (np.mean(X*y) -np.mean(X)* np.mean(y))/ (np.mean(X**2) - np.mean(X)**2)
b                                       

2.620538882402765

In [53]:
a = np.mean(y)- (b* np.mean(X))
a

444.1773573243596

In [54]:
#Вывод: y = 444,18 + 2,62*x   С увеличением зарплаты на 1 тыс., скоринговый балл возрастает на 2,62.

In [55]:
#Матричный метод


In [56]:
import seaborn as sns

In [57]:
X = X.reshape((n,1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [58]:
#X = np.hstack([np.ones((n,1)), X])
#X

In [59]:
y = y.reshape((n,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [60]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T@y)
B

array([[5.88982042]])

Задача № 2

In [106]:
X = zp
y = ks

In [113]:
def mse_(B1, y=y, X=X, n = 10):
    return np.sum((B1 * X - y)**2)/n

In [114]:
alpha = 1e-6
B1 = 0.1
n = 10

In [115]:
#mse = (1/n) * np.sum((B1*X-y)**2)
#mse

In [116]:
#mse_p = (2/n) * np.sum((B1*X-y)* X)
#mse_p

In [117]:
for i in  range(10):
    B1 -=alpha *(2/n) * np.sum((B1*X-y)*X)
    print('B1 = {}'.format(B1))

B1 = 0.25952808
B1 = 0.414660650906144
B1 = 0.5655188230595969
B1 = 0.7122203698240712
B1 = 0.8548798195302346
B1 = 0.9936085448867542
B1 = 1.1285148499277806
B1 = 1.2597040545647504
B1 = 1.387278576808517
B1 = 1.5113380127259965


In [119]:
for i in  range(500):
    B1 -=alpha *(2/n) * np.sum((B1*X-y)*X)
    if i%10 == 0:     
        print('Iteration:{i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

Iteration:0, B1=5.629340281237233, mse=57451.59938606899
Iteration:10, B1=5.692835432193034, mse=57051.433003054815
Iteration:20, B1=5.740852880272922, mse=56822.57946410561
Iteration:30, B1=5.777165500770666, mse=56691.69904907657
Iteration:40, B1=5.804626485478126, mse=56616.849068093856
Iteration:50, B1=5.825393526544474, mse=56574.04266614384
Iteration:60, B1=5.8410983528369655, mse=56549.561857680776
Iteration:70, B1=5.852974939784972, mse=56535.56138215128
Iteration:80, B1=5.861956466540286, mse=56527.55456671675
Iteration:90, B1=5.868748638669329, mse=56522.97550129376
Iteration:100, B1=5.873885137561711, mse=56520.35675226433
Iteration:110, B1=5.877769553381888, mse=56518.85910026643
Iteration:120, B1=5.880707096362074, mse=56518.00259913497
Iteration:130, B1=5.882928578088004, mse=56517.512769595625
Iteration:140, B1=5.884608547059329, mse=56517.232638059555
Iteration:150, B1=5.885879003490128, mse=56517.072431964974
Iteration:160, B1=5.8868397709626885, mse=56516.98081074626


Задача № 3

Для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа в случае, когда известно среднее квадратичное отклонение генеральной совокупности, а таблица критических точек распределения Стьюдента в случае, когда среднее квадратичное отлонение неизвестно.

Задача № 4

In [135]:
alpha = 5e-6
B1 = 0.1
n = 10
B0= 0.1

In [136]:
def mse_(B0, B1, y=y, X=X, n = 10):
    return np.sum((B0+ B1 * X - y)**2)/n

In [139]:
for i in  range(2000000):
    y_hat = B0+ B1*X
    B0-=alpha *(2/n) * np.sum((y_hat-y))
    B1 -=alpha *(2/n) * np.sum((y_hat-y)*X)
    if i%40000 == 0:     
        print('Iteration:{i}, B0={B0} B1={B1}, mse={mse}'.format(i=i, B0=B0, B1=B1, mse=mse_(B0,B1)))

Iteration:0, B0=444.1767132064056 B1=2.6205436233956876, mse=6470.414201281901
Iteration:40000, B0=444.17677535297895 B1=2.620543165969431, mse=6470.414201262576
Iteration:80000, B0=444.17683150345084 B1=2.6205427526771334, mse=6470.414201246795
Iteration:120000, B0=444.1768822363446 B1=2.620542379260605, mse=6470.414201233913
Iteration:160000, B0=444.1769280743655 B1=2.620542041872505, mse=6470.414201223401
Iteration:200000, B0=444.17696948978687 B1=2.6205417370366924, mse=6470.414201214814
Iteration:240000, B0=444.1770069093147 B1=2.620541461612425, mse=6470.414201207806
Iteration:280000, B0=444.1770407184866 B1=2.6205412127619705, mse=6470.414201202086
Iteration:320000, B0=444.1770712656414 B1=2.620540987921406, mse=6470.414201197414
Iteration:360000, B0=444.17709886550637 B1=2.6205407847741955, mse=6470.414201193604
Iteration:400000, B0=444.17712380244905 B1=2.620540601227273, mse=6470.414201190493
Iteration:440000, B0=444.17714633339455 B1=2.620540435389553, mse=6470.414201187949
