In [214]:
import numpy as np
import pandas as pd
from scipy.stats import norm
from scipy.stats import t

In [215]:
# Задача № 1
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [216]:
cov = np.cov(zp, ks, ddof = 0)
cov

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [217]:
cov1 = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
cov1

9157.839999999997

In [218]:
zp_std = np.std(zp, ddof = 0)
zp_std 

59.115480206118605

In [219]:
ks_std = np.std(ks, ddof = 0)
ks_std

174.55340157098058

In [220]:
cor_pirson = cov1/(zp_std * ks_std)
cor_pirson

0.8874900920739158

In [221]:
cor_pirson_2 = np.corrcoef(zp,ks)
cor_pirson_2

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [222]:
# Задача № 2
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
rel = 0.95


In [223]:
M = IQ.mean()
M

118.1

In [224]:
alpha = (1 - rel)/2
alpha 

0.025000000000000022

In [225]:
n = len(IQ)
n

10

In [226]:
std_IQ = np.std(IQ, ddof = 1)
std_IQ

10.54566788359614

In [228]:
t = t(df=9).ppf((0.025, 0.975))
t

array([-2.26215716,  2.26215716])

In [229]:
M + (t * std_IQ)/np.sqrt(n)

array([110.55608365, 125.64391635])

In [211]:
t(df=9).ppf((0.025, 0.975))

array([-2.26215716,  2.26215716])

In [235]:
#Задача № 3 

D = 25
n = 27
M = 174.2
rel = 0.95

In [236]:
std = np.sqrt(25)
std

5.0

In [237]:
alpha = (1 - rel)/2
alpha

0.025000000000000022

In [248]:
z = norm.ppf(alpha)
z

-1.959963984540054

In [252]:
M + (z * std)/ np.sqrt(n)

172.3140237765397

In [253]:
M - (z * std) / np.sqrt(n)

176.08597622346028